/* Generated by the Nim Compiler v1.6.10 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI603979780 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555124 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555458 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI603979779 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI805306371 = {size: 0,kind: 43,base: null,node: null,finalizer: null};
var NTI805306372 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555128 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555130 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555083 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555165 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554439 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554440 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555164 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555112 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555113 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555120 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555122 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI33555122 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555122.node = NNI33555122;
var NNI33555120 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555120.node = NNI33555120;
var NNI33555113 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555113.node = NNI33555113;
NTI33555164.base = NTI33555112;
NTI33555165.base = NTI33555112;
var NNI33555112 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555164, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554440, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554439, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554439, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555165, name: "up", sons: null}]};
NTI33555112.node = NNI33555112;
var NNI33555083 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555083.node = NNI33555083;
NTI33555112.base = NTI33555083;
NTI33555113.base = NTI33555112;
NTI33555120.base = NTI33555113;
NTI33555122.base = NTI33555120;
var NNI33555130 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555130.node = NNI33555130;
NTI33555130.base = NTI33555113;
var NNI33555128 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555128.node = NNI33555128;
NTI33555128.base = NTI33555113;
var NNI805306372 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI805306371, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI805306371, name: "a1", sons: null}]};
NTI805306372.node = NNI805306372;
var NNI603979779 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33555458, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33555458, name: "y", sons: null}]};
NTI603979779.node = NNI603979779;
var NNI33555124 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555124.node = NNI33555124;
NTI33555124.base = NTI33555113;
var NNI603979780 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33555458, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33555458, name: "y", sons: null}]};
NTI603979780.node = NNI603979780;
            var helper_805306422 = new Uint32Array([3198944359, 3630892171]);

function makeNimstrLit(c_33556801) {
    var result = [];
  for (var i = 0; i < c_33556801.length; ++i) {
  result[i] = c_33556801.charCodeAt(i);
  }
  return result;
}

function mnewString(len_33556893) {
    return new Array(len_33556893);
}

function toJSStr(s_33556807) {
          var Temporary5;
      var Temporary7;

  var result_33556808 = null;

  var res_33556842 = newSeq_33556825((s_33556807).length);
  var i_33556843 = 0;
  var j_33556844 = 0;
  Label1: do {
    Label2: while (true) {
    if (!(i_33556843 < (s_33556807).length)) break Label2;
      var c_33556845 = s_33556807[i_33556843];
      if ((c_33556845 < 128)) {
      res_33556842[j_33556844] = String.fromCharCode(c_33556845);
      i_33556843 += 1;
      }
      else {
      var helper_33556857 = newSeq_33556825(0);
      Label3: do {
        Label4: while (true) {
        if (!true) break Label4;
          var code_33556858 = c_33556845.toString(16);
          if ((((code_33556858) == null ? 0 : (code_33556858).length) == 1)) {
          helper_33556857.push("%0");;
          }
          else {
          helper_33556857.push("%");;
          }
          
          helper_33556857.push(code_33556858);;
          i_33556843 += 1;
          if (((s_33556807).length <= i_33556843)) Temporary5 = true; else {            Temporary5 = (s_33556807[i_33556843] < 128);          }          if (Temporary5) {
          break Label3;
          }
          
          c_33556845 = s_33556807[i_33556843];
        }
      } while (false);
++excHandler;
      Temporary7 = framePtr;
      try {
      res_33556842[j_33556844] = decodeURIComponent(helper_33556857.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
      framePtr = Temporary7;
      res_33556842[j_33556844] = helper_33556857.join("");
      lastJSError = prevJSError;
      } finally {
      framePtr = Temporary7;
      }
      }
      
      j_33556844 += 1;
    }
  } while (false);
  if (res_33556842.length < j_33556844) { for (var i = res_33556842.length ; i < j_33556844 ; ++i) res_33556842.push(null); }
         else { res_33556842.length = j_33556844; };
  result_33556808 = res_33556842.join("");

  return result_33556808;
}

function raiseException(e_33556667, ename_33556668) {
  e_33556667.name = ename_33556668;
  if ((excHandler == 0)) {
  unhandledException(e_33556667);
  }
  
  throw e_33556667;
}

function addInt(a_33556940, b_33556941) {
    var result = a_33556940 + b_33556941;
  checkOverflowInt(result);
  return result;
}

function chckRange(i_33557189, a_33557190, b_33557191) {
    var Temporary1;

  var result_33557192 = 0;

  BeforeRet: do {
    if (!(a_33557190 <= i_33557189)) Temporary1 = false; else {    Temporary1 = (i_33557189 <= b_33557191);    }  if (Temporary1) {
  result_33557192 = i_33557189;
  break BeforeRet;
  }
  else {
  raiseRangeError();
  }
  
  } while (false);

  return result_33557192;
}

function setConstr() {
    var result = {};
  for (var i = 0; i < arguments.length; ++i) {
    var x = arguments[i];
    if (typeof(x) == "object") {
    for (var j = x[0]; j <= x[1]; ++j) {
      result[j] = true;
    }
    } else {
    result[x] = true;
    }
  }
  return result;
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557140, src_33557141, ti_33557142) {
  var result_33557151 = null;

  switch (ti_33557142.kind) {
  case 21:
  case 22:
  case 23:
  case 5:
    if (!(isFatPointer_33557131(ti_33557142))) {
    result_33557151 = src_33557141;
    }
    else {
    result_33557151 = [src_33557141[0], src_33557141[1]];
    }
    
    break;
  case 19:
      if (dest_33557140 === null || dest_33557140 === undefined) {
    dest_33557140 = {};
    }
    else {
    for (var key in dest_33557140) { delete dest_33557140[key]; }
    }
    for (var key in src_33557141) { dest_33557140[key] = src_33557141[key]; }
    result_33557151 = dest_33557140;
  
    break;
  case 18:
  case 17:
    if (!((ti_33557142.base == null))) {
    result_33557151 = nimCopy(dest_33557140, src_33557141, ti_33557142.base);
    }
    else {
    if ((ti_33557142.kind == 17)) {
    result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {m_type: ti_33557142} : dest_33557140;
    }
    else {
    result_33557151 = (dest_33557140 === null || dest_33557140 === undefined) ? {} : dest_33557140;
    }
    }
    nimCopyAux(result_33557151, src_33557141, ti_33557142.node);
    break;
  case 24:
  case 4:
  case 27:
  case 16:
      if (src_33557141 === null) {
    result_33557151 = null;
    }
    else {
    if (dest_33557140 === null || dest_33557140 === undefined || dest_33557140.length != src_33557141.length) {
      dest_33557140 = new Array(src_33557141.length);
    }
    result_33557151 = dest_33557140;
    for (var i = 0; i < src_33557141.length; ++i) {
      result_33557151[i] = nimCopy(result_33557151[i], src_33557141[i], ti_33557142.base);
    }
    }
  
    break;
  case 28:
      if (src_33557141 !== null) {
    result_33557151 = src_33557141.slice(0);
    }
  
    break;
  default: 
    result_33557151 = src_33557141;
    break;
  }

  return result_33557151;
}

function chckIndx(i_33557184, a_33557185, b_33557186) {
    var Temporary1;

  var result_33557187 = 0;

  BeforeRet: do {
    if (!(a_33557185 <= i_33557184)) Temporary1 = false; else {    Temporary1 = (i_33557184 <= b_33557186);    }  if (Temporary1) {
  result_33557187 = i_33557184;
  break BeforeRet;
  }
  else {
  raiseIndexError(i_33557184, a_33557185, b_33557186);
  }
  
  } while (false);

  return result_33557187;
}
if (!Math.trunc) {
  Math.trunc = function(v) {
  v = +v;
  if (!isFinite(v)) return v;
  return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var state_805306381 = [{a0: 1773455756, a1: 4275166512}];
if (globalThis.utcInstance_838862218 === undefined) {
  globalThis.utcInstance_838862218 = [null];
}
if (globalThis.localInstance_838862219 === undefined) {
  globalThis.localInstance_838862219 = [null];
}
var objectID_1124073634 = [0];
var cnv_469762052 = document.getElementById("c1");
var ctx_469762053 = cnv_469762052.getContext('2d');

function toFloat_33556001(i_33556002) {
  var result_33556003 = 0.0;

  result_33556003 = i_33556002;

  return result_33556003;
}

function HEX2F_33557575(x_33557576, y_33557577) {
  var result_33557578 = 0.0;

  result_33557578 = (toFloat_33556001(x_33557576) / toFloat_33556001(y_33557577));

  return result_33557578;
}

function epochTime_838864210() {
  var result_838864211 = 0.0;

  result_838864211 = HEX2F_33557575(new Date().getTime(), 1000);

  return result_838864211;
}

function add_33556419(x_33556420, x_33556420_Idx, y_33556421) {
      if (x_33556420[x_33556420_Idx] === null) { x_33556420[x_33556420_Idx] = []; }
    var off = x_33556420[x_33556420_Idx].length;
    x_33556420[x_33556420_Idx].length += y_33556421.length;
    for (var i = 0; i < y_33556421.length; ++i) {
    x_33556420[x_33556420_Idx][off+i] = y_33556421.charCodeAt(i);
    }
}

function newSeq_33556825(len_33556827) {
  var result_33556828 = [];

  result_33556828 = new Array(len_33556827); for (var i = 0 ; i < len_33556827 ; ++i) { result_33556828[i] = null; }
  return result_33556828;
}

function unhandledException(e_33556663) {
  var buf_33556664 = [[]];
  if (!(((e_33556663.message).length == 0))) {
  buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception: "));;
  buf_33556664[0].push.apply(buf_33556664[0], e_33556663.message);;
  }
  else {
  buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("Error: unhandled exception"));;
  }
  
  buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit(" ["));;
  add_33556419(buf_33556664, 0, e_33556663.name);
  buf_33556664[0].push.apply(buf_33556664[0], makeNimstrLit("]\x0A"));;
  var cbuf_33556665 = toJSStr(buf_33556664[0]);
  framePtr = null;
    if (typeof(Error) !== "undefined") {
  throw new Error(cbuf_33556665);
  }
  else {
  throw cbuf_33556665;
  }
}

function raiseOverflow() {
  raiseException({message: makeNimstrLit("over- or underflow"), parent: null, m_type: NTI33555122, name: null, trace: [], up: null}, "OverflowDefect");
}

function checkOverflowInt(a_33556938) {
    if (a_33556938 > 2147483647 || a_33556938 < -2147483648) raiseOverflow();
}

function raiseRangeError() {
  raiseException({message: makeNimstrLit("value out of range"), parent: null, m_type: NTI33555130, name: null, trace: [], up: null}, "RangeDefect");
}

function addChars_251658415(result_251658417, result_251658417_Idx, x_251658418, start_251658419, n_251658420) {
  var old_251658421 = (result_251658417[result_251658417_Idx]).length;
  (result_251658417[result_251658417_Idx].length = chckRange(addInt(old_251658421, n_251658420), 0, 2147483647));
  Label1: do {
    var iHEX60gensym4_251658435 = 0;
    var i_469762163 = 0;
    Label2: do {
      Label3: while (true) {
      if (!(i_469762163 < n_251658420)) break Label3;
      iHEX60gensym4_251658435 = i_469762163;
      result_251658417[result_251658417_Idx][chckIndx(addInt(old_251658421, iHEX60gensym4_251658435), 0, (result_251658417[result_251658417_Idx]).length - 1)] = x_251658418.charCodeAt(chckIndx(addInt(start_251658419, iHEX60gensym4_251658435), 0, (x_251658418).length - 1));
      i_469762163 = addInt(i_469762163, 1);
      }
    } while (false);
  } while (false);
}

function addChars_251658411(result_251658413, result_251658413_Idx, x_251658414) {
  addChars_251658415(result_251658413, result_251658413_Idx, x_251658414, 0, ((x_251658414) == null ? 0 : (x_251658414).length));
}

function addInt_251658436(result_251658437, result_251658437_Idx, x_251658438) {
  addChars_251658411(result_251658437, result_251658437_Idx, ((x_251658438) + ""));
}

function addInt_251658457(result_251658458, result_251658458_Idx, x_251658459) {
  addInt_251658436(result_251658458, result_251658458_Idx, x_251658459);
}

function HEX24_335544323(x_335544324) {
  var result_335544325 = [[]];

  addInt_251658457(result_335544325, 0, x_335544324);

  return result_335544325[0];
}

function isFatPointer_33557131(ti_33557132) {
  var result_33557133 = false;

  BeforeRet: do {
  result_33557133 = !((ConstSet1[ti_33557132.base.kind] != undefined));
  break BeforeRet;
  } while (false);

  return result_33557133;
}

function nimCopyAux(dest_33557144, src_33557145, n_33557146) {
  switch (n_33557146.kind) {
  case 0:
    break;
  case 1:
      dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);
  
    break;
  case 2:
      for (var i = 0; i < n_33557146.sons.length; i++) {
    nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i]);
  }
  
    break;
  case 3:
      dest_33557144[n_33557146.offset] = nimCopy(dest_33557144[n_33557146.offset], src_33557145[n_33557146.offset], n_33557146.typ);
    for (var i = 0; i < n_33557146.sons.length; ++i) {
    nimCopyAux(dest_33557144, src_33557145, n_33557146.sons[i][1]);
    }
  
    break;
  }
}

function raiseIndexError(i_33556754, a_33556755, b_33556756) {
  var Temporary1;

  if ((b_33556756 < a_33556755)) {
  Temporary1 = makeNimstrLit("index out of bounds, the container is empty");
  }
  else {
  Temporary1 = (makeNimstrLit("index ") || []).concat(HEX24_335544323(i_33556754) || [],makeNimstrLit(" not in ") || [],HEX24_335544323(a_33556755) || [],makeNimstrLit(" .. ") || [],HEX24_335544323(b_33556756) || []);
  }
  
  raiseException({message: nimCopy(null, Temporary1, NTI33554439), parent: null, m_type: NTI33555128, name: null, trace: [], up: null}, "IndexDefect");
}

function rotl_805306399(x_805306400, k_805306401) {
  var result_805306402 = 0;

  result_805306402 = ((x_805306400 << k_805306401) | (x_805306400 >>> ((64 - k_805306401) >>> 0)));

  return result_805306402;
}

function next_805306411(r_805306412) {
  var result_805306413 = 0;

  var s0_805306414 = r_805306412.a0;
  var s1_805306415 = r_805306412.a1;
  result_805306413 = ((s0_805306414 + s1_805306415) >>> 0);
  s1_805306415 = (s1_805306415 ^ s0_805306414);
  r_805306412.a0 = ((rotl_805306399(s0_805306414, 55) ^ s1_805306415) ^ (s1_805306415 << 14));
  r_805306412.a1 = rotl_805306399(s1_805306415, 36);

  return result_805306413;
}

function skipRandomNumbers_805306420(s_805306421) {
  var s0_805306423 = 0;
  var s1_805306424 = 0;
  Label1: do {
    var i_805306433 = 0;
    var res_469762157 = 0;
    Label2: do {
      Label3: while (true) {
      if (!(res_469762157 <= 1)) break Label3;
      i_805306433 = res_469762157;
      Label4: do {
        var b_805306438 = 0;
        var i_469762155 = 0;
        Label5: do {
          Label6: while (true) {
          if (!(i_469762155 < 64)) break Label6;
          b_805306438 = i_469762155;
          if (!(((helper_805306422[chckIndx(i_805306433, 0, (helper_805306422).length - 1)] & (1 << b_805306438)) == 0))) {
          s0_805306423 = (s0_805306423 ^ s_805306421.a0);
          s1_805306424 = (s1_805306424 ^ s_805306421.a1);
          }
          
          var _ = next_805306411(s_805306421);
          i_469762155 = addInt(i_469762155, 1);
          }
        } while (false);
      } while (false);
      res_469762157 = addInt(res_469762157, 1);
      }
    } while (false);
  } while (false);
  s_805306421.a0 = s0_805306423;
  s_805306421.a1 = s1_805306424;
}

function initRand_805306587(seed_805306588) {
  var Temporary1;

  var result_805306589 = [({a0: 0, a1: 0})];

  if (!((seed_805306588 == 0))) {
  Temporary1 = seed_805306588;
  }
  else {
  Temporary1 = 2147483647;
  }
  
  var seed_805306595 = Temporary1;
  result_805306589[0].a0 = Math.floor(seed_805306595 / Math.pow(2, 16));
  result_805306589[0].a1 = (seed_805306595 & 65535);
  skipRandomNumbers_805306420(result_805306589[0]);
  var _ = next_805306411(result_805306589[0]);

  return result_805306589[0];
}

function initRand_805306612() {
  var result_805306613 = ({a0: 0, a1: 0});

  var time_805306614 = ((epochTime_838864210() * 1000.0) & 2147483647);
  result_805306613 = nimCopy(result_805306613, initRand_805306587(time_805306614), NTI805306372);

  return result_805306613;
}

function randomize_805306619() {
  state_805306381[0] = nimCopy(state_805306381[0], initRand_805306612(), NTI805306372);
}
randomize_805306619();
var circles_469762081 = [[{center: {x: 100.0, y: 50.0}, radius: 8.4, inertia: {x: 2.0, y: 0.0}, is_static: false}, {center: {x: 30.0, y: 10.0}, radius: 12.6, inertia: {x: -1.0, y: 0.0}, is_static: false}, {center: {x: 60.0, y: 20.0}, radius: 10.9, inertia: {x: 1.4, y: 0.0}, is_static: false}, {center: {x: 80.0, y: 50.0}, radius: 9.6, inertia: {x: -0.6, y: 0.0}, is_static: false}, {center: {x: 120.0, y: 30.0}, radius: 6.2, inertia: {x: 0.8, y: 0.0}, is_static: false}, {center: {x: 140.0, y: 40.0}, radius: 8.2, inertia: {x: 0.8, y: 0.0}, is_static: false}]];
var segments_469762086 = [[{a: {x: 10.0, y: 230.0}, b: {x: 330.0, y: 230.0}}, {a: {x: 60.0, y: 140.0}, b: {x: 160.0, y: 160.0}}, {a: {x: 280.0, y: 170.0}, b: {x: 305.0, y: 155.0}}, {a: {x: 190.0, y: 190.0}, b: {x: 250.0, y: 190.0}}, {a: {x: 10.0, y: 110.0}, b: {x: 10.0, y: 230.0}}, {a: {x: 330.0, y: 100.0}, b: {x: 330.0, y: 230.0}}]];
var gravity_469762087 = {x: 0.0, y: 1.6};
var restitution_469762088 = 0.8;
var dt_469762089 = 0.2;

function HEX2BHEX3D_469762194(x_469762196, x_469762196_Idx, y_469762197) {
  x_469762196[x_469762196_Idx] = (x_469762196[x_469762196_Idx] + y_469762197);
}

function apply_gravity_469762189(circle_469762191, g_469762192, dt_469762193) {
  HEX2BHEX3D_469762194(circle_469762191.inertia, "x", (g_469762192.x * dt_469762193));
  HEX2BHEX3D_469762194(circle_469762191.inertia, "y", (g_469762192.y * dt_469762193));
}

function min_33556194(x_33556195, y_33556196) {
  var Temporary1;
    var Temporary2;

  var result_33556197 = 0.0;

    if ((x_33556195 <= y_33556196)) Temporary2 = true; else {    Temporary2 = !((y_33556196 == y_33556196));    }  if (Temporary2) {
  Temporary1 = x_33556195;
  }
  else {
  Temporary1 = y_33556196;
  }
  
  result_33556197 = Temporary1;

  return result_33556197;
}

function max_33556202(x_33556203, y_33556204) {
  var Temporary1;
    var Temporary2;

  var result_33556205 = 0.0;

    if ((y_33556204 <= x_33556203)) Temporary2 = true; else {    Temporary2 = !((y_33556204 == y_33556204));    }  if (Temporary2) {
  Temporary1 = x_33556203;
  }
  else {
  Temporary1 = y_33556204;
  }
  
  result_33556205 = Temporary1;

  return result_33556205;
}

function collision_circle_segment_469762237(circle_469762239, segment_469762240, restitution_469762241) {
    var Temporary1;
    var Temporary2;
    var Temporary3;

  var cx_469762242 = circle_469762239.center.x;
  var cy_469762243 = circle_469762239.center.y;
  var r_469762244 = circle_469762239.radius;
  var vx_469762245 = circle_469762239.inertia.x;
  var vy_469762246 = circle_469762239.inertia.y;
  var a_469762247 = nimCopy(null, segment_469762240.a, NTI603979779);
  var b_469762248 = nimCopy(null, segment_469762240.b, NTI603979779);
  var min_x_469762249 = min_33556194(segment_469762240.a.x, segment_469762240.b.x);
  var min_y_469762250 = min_33556194(segment_469762240.a.y, segment_469762240.b.y);
  var max_x_469762251 = max_33556202(segment_469762240.a.x, segment_469762240.b.x);
  var max_y_469762252 = max_33556202(segment_469762240.a.y, segment_469762240.b.y);
    if (!(min_x_469762249 <= (cx_469762242 + r_469762244))) Temporary3 = false; else {    Temporary3 = ((cx_469762242 - r_469762244) <= max_x_469762251);    }    if (!Temporary3) Temporary2 = false; else {    Temporary2 = (min_y_469762250 <= (cy_469762243 + r_469762244));    }    if (!Temporary2) Temporary1 = false; else {    Temporary1 = ((cy_469762243 - r_469762244) <= max_y_469762252);    }  if (Temporary1) {
  var dx_469762253 = (segment_469762240.b.x - segment_469762240.a.x);
  var dy_469762254 = (segment_469762240.b.y - segment_469762240.a.y);
  var fx_469762255 = (cx_469762242 - segment_469762240.a.x);
  var fy_469762256 = (cy_469762243 - segment_469762240.a.y);
  var t_469762257 = (((fx_469762255 * dx_469762253) + (fy_469762256 * dy_469762254)) / ((dx_469762253 * dx_469762253) + (dy_469762254 * dy_469762254)));
  var proj_x_469762258 = 0.0;
  var proj_y_469762259 = 0.0;
  if ((t_469762257 < 0.0)) {
  proj_x_469762258 = a_469762247.x;
  proj_y_469762259 = a_469762247.y;
  }
  else {
  if ((1.0 < t_469762257)) {
  proj_x_469762258 = b_469762248.x;
  proj_y_469762259 = b_469762248.y;
  }
  else {
    proj_x_469762258 = (a_469762247.x + (t_469762257 * dx_469762253));
    proj_y_469762259 = (a_469762247.y + (t_469762257 * dy_469762254));
  }
  }
  var diff_x_469762260 = (cx_469762242 - proj_x_469762258);
  var diff_y_469762261 = (cy_469762243 - proj_y_469762259);
  var distance_469762262 = Math.sqrt(((diff_x_469762260 * diff_x_469762260) + (diff_y_469762261 * diff_y_469762261)));
  if ((distance_469762262 <= r_469762244)) {
  var normal_x_469762263 = ((cx_469762242 - proj_x_469762258) / distance_469762262);
  var normal_y_469762264 = ((cy_469762243 - proj_y_469762259) / distance_469762262);
  var dot_product_469762265 = ((vx_469762245 * normal_x_469762263) + (vy_469762246 * normal_y_469762264));
  if (!(circle_469762239.is_static)) {
  circle_469762239.inertia.x = (vx_469762245 - (((1.0 + restitution_469762241) * dot_product_469762265) * normal_x_469762263));
  circle_469762239.inertia.y = (vy_469762246 - (((1.0 + restitution_469762241) * dot_product_469762265) * normal_y_469762264));
  }
  
  var penetration_depth_469762266 = (r_469762244 - distance_469762262);
  if (!(circle_469762239.is_static)) {
  circle_469762239.center.x = (cx_469762242 + (normal_x_469762263 * penetration_depth_469762266));
  circle_469762239.center.y = (cy_469762243 + (normal_y_469762264 * penetration_depth_469762266));
  }
  }
  }
}

function sysFatal_218103842(message_218103845) {
  raiseException({message: nimCopy(null, message_218103845, NTI33554439), m_type: NTI33555124, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
}

function raiseAssert_218103840(msg_218103841) {
  sysFatal_218103842(msg_218103841);
}

function failedAssertImpl_218103864(msg_218103865) {
  raiseAssert_218103840(msg_218103865);
}

function normalize_vector_603979799(v_603979800) {
  var Temporary1;

  var result_603979801 = ({x: 0.0, y: 0.0});

  var magnitude_603979802 = Math.sqrt(((v_603979800.x * v_603979800.x) + (v_603979800.y * v_603979800.y)));
  if ((magnitude_603979802 == 0.0)) {
  Temporary1 = {x: 0.0, y: 0.0};
  }
  else {
  Temporary1 = {x: (v_603979800.x / magnitude_603979802), y: (v_603979800.y / magnitude_603979802)};
  }
  
  result_603979801 = nimCopy(result_603979801, Temporary1, NTI603979780);

  return result_603979801;
}

function HEX2DHEX3D_469762297(x_469762299, x_469762299_Idx, y_469762300) {
  x_469762299[x_469762299_Idx] = (x_469762299[x_469762299_Idx] - y_469762300);
}

function collision_circle_circle_469762283(circle1_469762285, circle2_469762286, restitution_469762287) {
  var dx_469762288 = (circle2_469762286.center.x - circle1_469762285.center.x);
  var dy_469762289 = (circle2_469762286.center.y - circle1_469762285.center.y);
  var distance_469762290 = Math.sqrt(((dx_469762288 * dx_469762288) + (dy_469762289 * dy_469762289)));
  var overlap_469762291 = ((circle1_469762285.radius + circle2_469762286.radius) - distance_469762290);
  if ((0.0 < overlap_469762291)) {
  var normal_469762292 = normalize_vector_603979799({x: dx_469762288, y: dy_469762289});
  var relative_velocity_x_469762293 = (circle1_469762285.inertia.x - circle2_469762286.inertia.x);
  var relative_velocity_y_469762294 = (circle1_469762285.inertia.y - circle2_469762286.inertia.y);
  var dot_product_469762295 = ((relative_velocity_x_469762293 * normal_469762292.x) + (relative_velocity_y_469762294 * normal_469762292.y));
  if ((0.0 < dot_product_469762295)) {
  var impulse_469762296 = (((1.0 + restitution_469762287) * dot_product_469762295) / (circle1_469762285.radius + circle2_469762286.radius));
  if (!(circle1_469762285.is_static)) {
  HEX2DHEX3D_469762297(circle1_469762285.inertia, "x", (impulse_469762296 * normal_469762292.x));
  HEX2DHEX3D_469762297(circle1_469762285.inertia, "y", (impulse_469762296 * normal_469762292.y));
  }
  if (!(circle2_469762286.is_static)) {
  HEX2BHEX3D_469762194(circle2_469762286.inertia, "x", (impulse_469762296 * normal_469762292.x));
  HEX2BHEX3D_469762194(circle2_469762286.inertia, "y", (impulse_469762296 * normal_469762292.y));
  }
  var separation_469762313 = (overlap_469762291 / 2.0);
  if (!(circle1_469762285.is_static)) {
  HEX2DHEX3D_469762297(circle1_469762285.center, "x", (normal_469762292.x * separation_469762313));
  HEX2DHEX3D_469762297(circle1_469762285.center, "y", (normal_469762292.y * separation_469762313));
  }
  if (!(circle2_469762286.is_static)) {
  HEX2BHEX3D_469762194(circle2_469762286.center, "x", (normal_469762292.x * separation_469762313));
  HEX2BHEX3D_469762194(circle2_469762286.center, "y", (normal_469762292.y * separation_469762313));
  }
  }
  }
}

function update_circles_469762168(circles_469762170, circles_469762170_Idx, segments_469762171, gravity_469762172, dt_469762173, restitution_469762174) {
  Label1: do {
    var i_469762183 = 0;
    var colontmp__469762409 = 0;
    colontmp__469762409 = (circles_469762170[circles_469762170_Idx]).length;
    var i_469762410 = 0;
    Label2: do {
      Label3: while (true) {
      if (!(i_469762410 < colontmp__469762409)) break Label3;
      i_469762183 = i_469762410;
      if (!(circles_469762170[circles_469762170_Idx][chckIndx(i_469762183, 0, (circles_469762170[circles_469762170_Idx]).length - 1)].is_static)) {
      apply_gravity_469762189(circles_469762170[circles_469762170_Idx][chckIndx(i_469762183, 0, (circles_469762170[circles_469762170_Idx]).length - 1)], gravity_469762172, dt_469762173);
      HEX2BHEX3D_469762194(circles_469762170[circles_469762170_Idx][chckIndx(i_469762183, 0, (circles_469762170[circles_469762170_Idx]).length - 1)].center, "x", (circles_469762170[circles_469762170_Idx][chckIndx(i_469762183, 0, (circles_469762170[circles_469762170_Idx]).length - 1)].inertia.x * dt_469762173));
      HEX2BHEX3D_469762194(circles_469762170[circles_469762170_Idx][chckIndx(i_469762183, 0, (circles_469762170[circles_469762170_Idx]).length - 1)].center, "y", (circles_469762170[circles_469762170_Idx][chckIndx(i_469762183, 0, (circles_469762170[circles_469762170_Idx]).length - 1)].inertia.y * dt_469762173));
      Label4: do {
        var segment_469762231 = ({a: ({x: 0.0, y: 0.0}), b: ({x: 0.0, y: 0.0})});
        var i_469762406 = 0;
        var L_469762407 = (segments_469762171).length;
        Label5: do {
          Label6: while (true) {
          if (!(i_469762406 < L_469762407)) break Label6;
          segment_469762231 = segments_469762171[chckIndx(i_469762406, 0, (segments_469762171).length - 1)];
          collision_circle_segment_469762237(circles_469762170[circles_469762170_Idx][chckIndx(i_469762183, 0, (circles_469762170[circles_469762170_Idx]).length - 1)], segment_469762231, restitution_469762174);
          i_469762406 = addInt(i_469762406, 1);
          if (!(((segments_469762171).length == L_469762407))) {
          failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
          }
          }
        } while (false);
      } while (false);
      }
      i_469762410 = addInt(i_469762410, 1);
      }
    } while (false);
  } while (false);
  Label7: do {
    var i_469762274 = 0;
    var colontmp__469762418 = 0;
    colontmp__469762418 = (circles_469762170[circles_469762170_Idx]).length;
    var i_469762419 = 0;
    Label8: do {
      Label9: while (true) {
      if (!(i_469762419 < colontmp__469762418)) break Label9;
      i_469762274 = i_469762419;
      Label10: do {
        var j_469762282 = 0;
        var colontmp__469762414 = 0;
        var colontmp__469762415 = 0;
        colontmp__469762414 = addInt(i_469762274, 1);
        colontmp__469762415 = (circles_469762170[circles_469762170_Idx]).length;
        var i_469762416 = colontmp__469762414;
        Label11: do {
          Label12: while (true) {
          if (!(i_469762416 < colontmp__469762415)) break Label12;
          j_469762282 = i_469762416;
          collision_circle_circle_469762283(circles_469762170[circles_469762170_Idx][chckIndx(i_469762274, 0, (circles_469762170[circles_469762170_Idx]).length - 1)], circles_469762170[circles_469762170_Idx][chckIndx(j_469762282, 0, (circles_469762170[circles_469762170_Idx]).length - 1)], restitution_469762174);
          i_469762416 = addInt(i_469762416, 1);
          }
        } while (false);
      } while (false);
      i_469762419 = addInt(i_469762419, 1);
      }
    } while (false);
  } while (false);
}

function draw_bg_469762054() {
  ctx_469762053.beginPath();
  ctx_469762053.fillStyle = 'rgb(255, 255, 255)';
  ctx_469762053.rect(0, 0, 340, 240);
  ctx_469762053.fill();
}

function draw_c_469762360(c_469762362) {
  ctx_469762053.beginPath();
  ctx_469762053.fillStyle = 'rgb(240, 180, 20)';
  ctx_469762053.arc(c_469762362.center.x, c_469762362.center.y, c_469762362.radius, 0, 2 * Math.PI);
  ctx_469762053.fill();
}

function draw_ln_469762064(s_469762065) {
  ctx_469762053.beginPath();
  ctx_469762053.strokeStyle = 'rgb(10, 230, 80)';
  ctx_469762053.lineWidth = 1.4;
  ctx_469762053.moveTo(s_469762065.a.x, s_469762065.a.y);
  ctx_469762053.lineTo(s_469762065.b.x, s_469762065.b.y);
  ctx_469762053.stroke();
}

function animate_469762167() {
  update_circles_469762168(circles_469762081, 0, segments_469762086[0], gravity_469762087, dt_469762089, restitution_469762088);
  draw_bg_469762054();
  Label1: do {
    var circle_469762359 = ({center: ({x: 0.0, y: 0.0}), radius: 0.0, inertia: ({x: 0.0, y: 0.0}), is_static: false});
    var i_469762396 = 0;
    var L_469762397 = (circles_469762081[0]).length;
    Label2: do {
      Label3: while (true) {
      if (!(i_469762396 < L_469762397)) break Label3;
      circle_469762359 = circles_469762081[0][chckIndx(i_469762396, 0, (circles_469762081[0]).length - 1)];
      draw_c_469762360(circle_469762359);
      i_469762396 = addInt(i_469762396, 1);
      if (!(((circles_469762081[0]).length == L_469762397))) {
      failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
      }
      }
    } while (false);
  } while (false);
  Label4: do {
    var segment_469762366 = ({a: ({x: 0.0, y: 0.0}), b: ({x: 0.0, y: 0.0})});
    var i_469762401 = 0;
    var L_469762402 = (segments_469762086[0]).length;
    Label5: do {
      Label6: while (true) {
      if (!(i_469762401 < L_469762402)) break Label6;
      segment_469762366 = segments_469762086[0][chckIndx(i_469762401, 0, (segments_469762086[0]).length - 1)];
      draw_ln_469762064(segment_469762366);
      i_469762401 = addInt(i_469762401, 1);
      if (!(((segments_469762086[0]).length == L_469762402))) {
      failedAssertImpl_218103864(makeNimstrLit("iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it"));
      }
      }
    } while (false);
  } while (false);
}
setInterval(animate_469762167, 50);
